FROM ubuntu:xenial
RUN apt update && apt install -y pkg-config qt5-default libfftw3-dev wget cmake make build-essential libz-dev nano git
WORKDIR /tmp
COPY deps/install-opencv.sh /tmp/install-opencv.sh

RUN /tmp/install-opencv.sh && rm -rfv /tmp/*

VOLUME ["/build"]

WORKDIR /build
CMD qmake . && make -j4 
