#ifndef HOLMOS_IMGLIB_GLOBAL_H
#define HOLMOS_IMGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOLMOS_IMGLIB_LIBRARY)
#  define HOLMOS_IMGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOLMOS_IMGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOLMOS_IMGLIB_GLOBAL_H
